<a href="https://colab.research.google.com/github/aleylani/Python/blob/main/exercises/10_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

---
These are introductory exercises in Python with focus in **Numpy**.

<p class = "alert alert-info" role="alert"><b>Remember</b> to use <b>descriptive variable names</b> in order to get readable code </p>

<p class = "alert alert-info" role="alert"><b>Remember</b> to format your answers in a neat way using <b>f-strings</b>

<p class = "alert alert-info" role="alert"><b>Remember</b> to format your input questions in a pedagogical way to guide the user

The number of stars (\*), (\*\*), (\*\*\*) denotes the difficulty level of the task

---

## 1. Dice simulations (*)

Simulations of one die,  

&nbsp; a) Calculate theoretical mean of a dice (six-sided) (*)

&nbsp; b) Now do simulations of

- 10
- 100
- 1000
- 10000
- 100000
- 1000000
- 10000000

number of dices and plot their means. (*)

<details>

<summary>Answer </summary>

a)
```
3.5
```

b)

<img src="../assets/numpy_1b.png" width = 300>

</details>




In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Theoretical mean
theoretical_mean = np.mean([1, 2, 3, 4, 5, 6])
print(f"Theoretical mean of a fair six-sided die: {theoretical_mean}")

# Step 2: Simulations for different number of dice
num_dice = [10, 100, 1000, 10000, 100000, 1000000, 10000000]
simulated_means = []

for n in num_dice:
    rolls = np.random.randint(1, 7, size=n)  # Simulate n dice rolls
    mean_roll = np.mean(rolls)               # Calculate the mean of the rolls
    simulated_means.append(mean_roll)
    print(f"Mean for {n} dice rolls: {mean_roll}")

Theoretical mean of a fair six-sided die: 3.5
Mean for 10 dice rolls: 3.9
Mean for 100 dice rolls: 3.68
Mean for 1000 dice rolls: 3.449
Mean for 10000 dice rolls: 3.4845
Mean for 100000 dice rolls: 3.50654
Mean for 1000000 dice rolls: 3.499783
Mean for 10000000 dice rolls: 3.4994632


---
## 2. Several dices (**)

&nbsp; a) Make a sample space for the sum of two dices, i.e. all possible outcomes of these dices. (*)

&nbsp; b) Count the number of each values in the sample space (*)

&nbsp; c) Now calculate the frequency $f_i$ for each unique value. Also check that the sum of frequencies sums to 1, i.e. $\sum_i f_i = 1$. (*)

&nbsp; d) Make a bar chart of the sum of two dices, with frequencies in y and unique values in x. This is a probability distribution of the sum of your two dices. (*)

&nbsp; e) Now make barplots in subplots of sum of dices for 1 dice, 2 dices, 3 dices and 4 dices. What is the pattern that you see? (**)

<details>

<summary>Hint</summary>

a)

Here are some potentially useful methods:

```py

np.meshgrid(), np.add.reduce(), np.unique()

```

c)

Divide by the total number of outcomes


</details>

<details>

<summary>Answer</summary>


a)

Sample space

```
[[ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]
 [ 6  7  8  9 10 11]
 [ 7  8  9 10 11 12]]
```

b)

Unique values:
```
[ 2  3  4  5  6  7  8  9 10 11 12]
```

Count:
```
[1 2 3 4 5 6 5 4 3 2 1]
```

c)

```
[0.028 0.056 0.083 0.111 0.139 0.167 0.139 0.111 0.083 0.056 0.028]
```

d)


<img src="../assets/numpy2d.png" width = 300>


e)

<img src="../assets/numpy2e.png" width = 500>


We see that when we sum several uniformly distributed random variables we will approach the normal distribution. This is called the central limit theorem, which we will come back to in the statistics course.

</details>